defmodule ExLemonway.CardFactory do
  @moduledoc """
  Factory for Card.

  It's automatically generated by `mix specs.gen.model Card`
  Dont' edit this file manually, to make any changes, please update:
  `specs/directkit/model/card.json`
  """

  alias ExLemonway.Card

  defmacro __using__(_opts) do
    quote do
      def card_factory(params \\ %{}) do
        id = id(ExLemonway.CardFactory)

        %Card{
          extra: ExLemonway.Factory.build(:card_extra),
          id: gen_value("string", "ID", id)
        }
        |> Map.merge(params)
      end
    end
  end
end
