defmodule ExLemonway.CardExtraFactory do
  @moduledoc """
  Factory for CardExtra.

  It's automatically generated by `mix specs.gen.model CardExtra`
  Dont' edit this file manually, to make any changes, please update:
  `specs/directkit/model/card_extra.json`
  """

  alias ExLemonway.CardExtra

  defmacro __using__(_opts) do
    quote do
      def card_extra_factory(params \\ %{}) do
        id = id(ExLemonway.CardExtraFactory)

        %CardExtra{
          auth: gen_value("string", "AUTH", id),
          ctry: gen_value("string", "CTRY", id),
          exp: gen_value("string", "EXP", id),
          i_s3_ds: gen_value("string", "IS3DS", id),
          num: gen_value("string", "NUM", id),
          typ: gen_value("string", "TYP", id)
        }
        |> Map.merge(params)
      end
    end
  end
end
