defmodule ExLemonway.WalletLimitFactory do
  @moduledoc """
  Factory for WalletLimit.

  It's automatically generated by `mix specs.gen.model WalletLimit`
  Dont' edit this file manually, to make any changes, please update:
  `specs/directkit/model/wallet_limit.json`
  """

  alias ExLemonway.WalletLimit

  defmacro __using__(_opts) do
    quote do
      def wallet_limit_factory(params \\ %{}) do
        id = id(ExLemonway.WalletLimitFactory)

        %WalletLimit{
          amountmoneyinallowed: gen_value("string", "AMOUNTMONEYINALLOWED", id),
          totalmoneyinallowed: gen_value("string", "TOTALMONEYINALLOWED", id)
        }
        |> Map.merge(params)
      end
    end
  end
end
