defmodule ExLemonway.Card do
  @moduledoc """
  Model for Card.

  It's automatically generated by `mix specs.gen.model Card`
  Dont' edit this file manually, to make any changes, please update:
  `specs/directkit/model/card.json`
  """

  defstruct extra: nil,
            id: nil
end
