defmodule ExLemonway.CardExtra do
  @moduledoc """
  Model for CardExtra.

  It's automatically generated by `mix specs.gen.model CardExtra`
  Dont' edit this file manually, to make any changes, please update:
  `specs/directkit/model/card_extra.json`
  """

  defstruct auth: nil,
            ctry: nil,
            exp: nil,
            i_s3_ds: nil,
            num: nil,
            typ: nil
end
