defmodule ExLemonway.WalletLimit do
  @moduledoc """
  Model for WalletLimit.

  It's automatically generated by `mix specs.gen.model WalletLimit`
  Dont' edit this file manually, to make any changes, please update:
  `specs/directkit/model/wallet_limit.json`
  """

  defstruct amountmoneyinallowed: nil,
            totalmoneyinallowed: nil
end
