defmodule ExLemonway.Wallet do
  @moduledoc """
  Model for Wallet.

  It's automatically generated by `mix specs.gen.model Wallet`
  Dont' edit this file manually, to make any changes, please update:
  `specs/directkit/model/wallet.json`
  """

  defstruct bal: nil,
            blocked: nil,
            birth_city: nil,
            birth_country: nil,
            birth_date: nil,
            cards: [],
            city: nil,
            client_title: nil,
            company_description: nil,
            company_identification_number: nil,
            company_name: nil,
            company_website: nil,
            country: nil,
            docs: [],
            email: nil,
            first_name: nil,
            ibans: [],
            id: nil,
            is_company: nil,
            is_one_time_customer: nil,
            is_tech_wallet: nil,
            limits: nil,
            lwid: nil,
            last_name: nil,
            mobile_number: nil,
            name: nil,
            nationality: nil,
            phone_number: nil,
            post_code: nil,
            sddmandates: [],
            status: nil,
            street: nil
end
