defmodule <%= inspect specs.module %> do
  @moduledoc """
  Model for <%= specs.name %>.

  It's automatically generated by `mix specs.gen.model <%= specs.name %>`
  Dont' edit this file manually, to make any changes, please update:
  `<%= specs.specs_file %>`
  """

  <% lp = "\n    " %>
  <% fields = for {field, type} <- specs.specs_fields, do: Macro.underscore(field) <> ": #{list_or_nil.(type)}" %>
  defstruct [ <%= lp <> Enum.join(fields, ",#{lp}") %>
  ]
end
